server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: customer-service
        uri: http://localhost:8081/customer-service/
        #uri: lb://customer-service
        predicates:
        - Path=/customersAPI/**
      - id: address-service
        uri: http://localhost:8082/address-service/
        #uri: lb://address-service
        predicates:
        - Path=/addressAPI/**